#!/usr/bin/env bash
set -euo pipefail

alias crisai='python -m crisai.cli.main'

cd "$(dirname "$0")"
source .venv/bin/activate
export PYTHONPATH=./src

if [ -f .env ]; then
  set -a
  source .env
  set +a
fi

#exec python -m crisai.cli.main "$@"
crisai chat --pipeline --verbose
