#!/usr/bin/env bash
# Stop the crisAI hcom development team.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export HCOM_DIR="${HCOM_DIR:-$ROOT_DIR/.hcom}"
ASSIGNMENTS="$ROOT_DIR/reference/development/session_assignments.local.yaml"

if ! command -v hcom >/dev/null 2>&1; then
  echo "Missing required command: hcom" >&2
  exit 1
fi

snapshot_assignments() {
  [[ -f "$ASSIGNMENTS" ]] || return 0

  local json tmp
  if ! json="$(hcom list --json 2>/dev/null)"; then
    echo "Could not read hcom session list; keeping existing assignments." >&2
    return 0
  fi

  tmp="$(mktemp)"
  ASSIGNMENTS_PATH="$ASSIGNMENTS" HCOM_JSON="$json" python - <<'PY' >"$tmp"
import json
import os
import subprocess
from datetime import datetime, timezone

assignments_path = os.environ["ASSIGNMENTS_PATH"]
agents = json.loads(os.environ.get("HCOM_JSON") or "[]")

agent_by_name = {}
for agent in agents:
    for key in (agent.get("name"), agent.get("base_name")):
        if key:
            agent_by_name[key] = agent


def stopped_agent(name):
    """Return resumable hcom details for an already stopped agent."""
    try:
        output = subprocess.check_output(
            ["hcom", "list", "--stopped", name],
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except (OSError, subprocess.CalledProcessError):
        return {}

    detail = {"base_name": name, "name": name, "status": "stopped"}
    field_map = {
        "Session": "session_id",
        "Transcript": "transcript_path",
        "Tool": "tool",
        "Tag": "tag",
        "Directory": "directory",
    }
    for line in output.splitlines():
        stripped = line.strip()
        if ":" not in stripped:
            continue
        key, value = stripped.split(":", 1)
        mapped = field_map.get(key.strip())
        if mapped and value.strip():
            detail[mapped] = value.strip()
    return detail if detail.get("session_id") else {}

header = []
sessions = []
current = None
in_sessions = False

with open(assignments_path, encoding="utf-8") as handle:
    for raw_line in handle:
        line = raw_line.rstrip("\n")
        if line == "sessions:":
            in_sessions = True
            continue
        if not in_sessions:
            header.append(line)
            continue
        if line.startswith("  ") and not line.startswith("    ") and line.endswith(":"):
            if current:
                sessions.append(current)
            current = {"name": line.strip()[:-1]}
            continue
        if current and line.startswith("    ") and ":" in line:
            key, value = line.strip().split(":", 1)
            current[key] = value.strip()

if current:
    sessions.append(current)

now = datetime.now(timezone.utc).isoformat()
print("# Generated by scripts/hcom_stop.sh. This file is local and ignored by git.")
for line in header:
    if not line.startswith("#") and not line.startswith("generated_at:"):
        print(line)
print(f'stopped_at: "{now}"')
print("sessions:")

for session in sessions:
    name = session["name"]
    agent = agent_by_name.get(name, {}) or stopped_agent(name)
    provider_session_id = agent.get("session_id") or session.get("provider_session_id")
    transcript_path = agent.get("transcript_path") or session.get("transcript_path")
    full_name = agent.get("name") or session.get("hcom_session_id") or name
    status = agent.get("status") or session.get("status") or "stopped"

    print(f"  {name}:")
    for key in ("role", "area", "provider", "tag"):
        if session.get(key):
            print(f"    {key}: {session[key]}")
    print(f"    hcom_session_id: {full_name}")
    if provider_session_id:
        print(f"    provider_session_id: {provider_session_id}")
    if transcript_path:
        print(f"    transcript_path: {transcript_path}")
    print(f"    previous_status: {status}")
    print("    status: stopped")
PY
  mv "$tmp" "$ASSIGNMENTS"
  echo "Saved resumable hcom session assignments to $ASSIGNMENTS"
}

snapshot_assignments

for tag in crisai-orchestrator crisai-runtime crisai-gem crisai-web; do
  hcom kill "tag:$tag" || true
done
