#!/usr/bin/env bash
# Launch the crisAI hcom development team.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HCOM_DIR="${HCOM_DIR:-$ROOT_DIR/.hcom}"
ASSIGNMENTS="$ROOT_DIR/reference/development/session_assignments.local.yaml"
DRY_RUN=0
HEADLESS=0
EXTRA_ARGS=()

usage() {
  cat <<'EOF'
Usage: scripts/hcom_start.sh [--dry-run] [--headless] [-- extra hcom args]

Launches:
  - one Codex orchestrator from repo root
  - runtime Codex + Claude from runtime/
  - Gem Codex + Claude from gem/
  - web Codex + Claude from web/

State:
  HCOM_DIR defaults to ./.hcom and is ignored by git.
  Generated session assignments are written to
  reference/development/session_assignments.local.yaml.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --headless)
      HEADLESS=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --)
      shift
      EXTRA_ARGS+=("$@")
      break
      ;;
    *)
      EXTRA_ARGS+=("$1")
      shift
      ;;
  esac
done

require_bin() {
  local bin="$1"
  if ! command -v "$bin" >/dev/null 2>&1; then
    echo "Missing required command: $bin" >&2
    exit 1
  fi
}

role_prompt() {
  local role_file="$1"
  cat "$ROOT_DIR/$role_file"
  printf '\n\n'
  cat <<'EOF'
Start by identifying your hcom session name, stable role, area, and peer from
reference/development/session_assignments.local.yaml when it exists. Use hcom
for concise coordination and the Claude memory MCP server for durable task
context. Do not store secrets in memory.
EOF
}

extract_names() {
  sed -n 's/^Names: //p' | tr ' ' '\n' | sed '/^$/d'
}

run_cmd() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf 'DRY RUN:' >&2
    printf ' %q' "$@" >&2
    printf '\n' >&2
    return 0
  fi
  "$@"
}

launch_agent() {
  local role="$1"
  local provider="$2"
  local tag="$3"
  local launch_dir="$4"
  local role_file="$5"
  local area="$6"

  local prompt
  prompt="$(role_prompt "$role_file")"

  local cmd=(hcom "$provider" --tag "$tag" --dir "$ROOT_DIR/$launch_dir" --hcom-prompt "$prompt")
  if [[ "$HEADLESS" -eq 1 ]]; then
    cmd+=(--headless)
  fi
  if [[ "${#EXTRA_ARGS[@]}" -gt 0 ]]; then
    cmd+=("${EXTRA_ARGS[@]}")
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    run_cmd "${cmd[@]}"
    echo "dry-run-$role"
    return 0
  fi

  local output
  output="$("${cmd[@]}" 2>&1)"
  printf '%s\n' "$output" >&2
  local name
  name="$(printf '%s\n' "$output" | extract_names | head -n 1)"
  if [[ -z "$name" ]]; then
    echo "Could not parse hcom launched name for role $role." >&2
    exit 1
  fi
  printf '%s\n' "$name"
}

write_assignment() {
  local name="$1"
  local role="$2"
  local area="$3"
  local provider="$4"
  local tag="$5"

  cat >>"$ASSIGNMENTS" <<EOF
  $name:
    role: $role
    area: $area
    provider: $provider
    tag: $tag
    status: active
EOF
}

require_bin hcom
require_bin codex
require_bin claude

export HCOM_DIR
mkdir -p "$HCOM_DIR"

if [[ "$DRY_RUN" -eq 0 ]]; then
  hcom config name_export HCOM_NAME >/dev/null
  hcom config auto_subscribe collision,created,blocked >/dev/null
  hcom config auto_approve true >/dev/null
fi

mkdir -p "$(dirname "$ASSIGNMENTS")"
cat >"$ASSIGNMENTS" <<EOF
# Generated by scripts/hcom_start.sh. This file is local and ignored by git.
# Random hcom names are session handles only; roles are stable.
hcom_dir: $HCOM_DIR
generated_at: "$(date -Is)"
sessions:
EOF

name="$(launch_agent orchestrator_codex codex crisai-orchestrator . reference/development/roles/orchestrator_codex.md root)"
write_assignment "$name" orchestrator_codex root codex crisai-orchestrator

name="$(launch_agent runtime_codex codex crisai-runtime runtime reference/development/roles/runtime_codex.md runtime)"
write_assignment "$name" runtime_codex runtime codex crisai-runtime

name="$(launch_agent runtime_claude claude crisai-runtime runtime reference/development/roles/runtime_claude.md runtime)"
write_assignment "$name" runtime_claude runtime claude crisai-runtime

name="$(launch_agent gem_codex codex crisai-gem gem reference/development/roles/gem_codex.md gem)"
write_assignment "$name" gem_codex gem codex crisai-gem

name="$(launch_agent gem_claude claude crisai-gem gem reference/development/roles/gem_claude.md gem)"
write_assignment "$name" gem_claude gem claude crisai-gem

name="$(launch_agent web_codex codex crisai-web web reference/development/roles/web_codex.md web)"
write_assignment "$name" web_codex web codex crisai-web

name="$(launch_agent web_claude claude crisai-web web reference/development/roles/web_claude.md web)"
write_assignment "$name" web_claude web claude crisai-web

echo "hcom team assignment written to $ASSIGNMENTS"
if [[ "$DRY_RUN" -eq 0 ]]; then
  hcom list
fi
